## Please, read the readme file for more information about developing via container.
version: '3.8'
services:
  dev:
    build: ./dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: /bin/sh -c "while sleep 1000; do :; done"
