name: "🐞 Bug Report"
description: File a bug report
title: "[BUG]: <Title>"
labels: ["kind/bug", "status/triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please search the issue list first as there is a chance that the same issue has been reported.
        Bug reports are tagged `kind/bug`.
        If you find a similar issue, add a thumbs-up to vote for it and optionally add a comment to be part of the conversation.

  - type: textarea
    attributes:
      label: What version of Ratel are you using?
      description: Ratel build info is found in the Help tab.
      placeholder: |
        Paste here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: What you did.
      description: Actions you performed.
      placeholder: |
        Paste here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: What happened.
      description: Current behavior
      placeholder: |
        Type here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What you expect to happen.
      description: Enter details about your expectations.
      placeholder: |
        Type here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Can we reproduce the issue?
      description: What steps will reproduce the issue.
      placeholder: |
        Type here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Tell us anything else you think we should know.
