# Ratel binary and test environment are built from Dockerfile and Dockerfile.test
# Dgraph server versions are set to 'latest' and can be overriden by setting
#  DGRAPH_VERSION env var
services:
  ratel:
    build: ../../..
    ports:
      - 8000

  test:
    build:
      context: ../../..
      dockerfile: test.Dockerfile
    privileged: true
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep 9999999999d & wait"]
    environment:
      TEST_DGRAPH_SERVER: http://alpha:8080
      TEST_RATEL_URL: http://ratel:8000?local

  zero:
    image: dgraph/dgraph:${DGRAPH_VERSION}
    ports:
      - 5080
      - 6080
    restart: on-failure
    command: dgraph zero --my=zero:5080

  alpha:
    image: dgraph/dgraph:${DGRAPH_VERSION}
    volumes:
      - ./acl-secret.txt:/secrets/acl-secret.txt
    ports:
      - 8080
      - 9080
    restart: on-failure
    command:
      dgraph alpha --my=alpha:7080 --zero=zero:5080 --acl='secret-file=/secrets/acl-secret.txt'
      --security='whitelist=0.0.0.0/0'
